<?php

/**
 * @File
 * Example custom module for Drupal 8.
 * @author Mark Newton
 */

/**
 * Implementing hook_menu().
 */
function fix_config_menu() {
  // The paths given here need to match the ones in example.routing.yml exactly.
  $items['/fix_config/fix'] = array(
    'title' => 'First page',
    'description' => 'This is a example page.',
    // The name of the route from example.routing.yml
    'route' => 'fix_config/fix',
  );
  return $items;
}